FROM continuumio/miniconda3

RUN conda install -c conda-forge cartopy -y \
		&& conda install  xarray  numpy pandas matplotlib imageio -y

RUN apt update && apt install -y unzip zip

RUN mkdir /srv/topoflow
ADD . /srv/topoflow
ENV TOPOFLOW_TAG v0.0.2
ADD https://raw.githubusercontent.com/mintproject/Topoflow_Viz/$TOPOFLOW_TAG/topo_viz.py /usr/bin/
RUN cd /srv/topoflow && pip install .
