FROM continuumio/miniconda3

RUN conda install -c conda-forge cartopy -y \
		&& conda install  xarray  numpy pandas matplotlib imageio -y

RUN mkdir /srv/topoflow
ADD . /srv/topoflow
RUN cd /srv/topoflow && pip install .
